services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: bnpl_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  web:
    build: .
    volumes:
      - ./src:/app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://user:password@db:5432/bnpl_db
    depends_on:
      - db